[application]

# App name
name = "baxterjo_webapp"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "docs"

# The static resource path
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Jordan Baxter"

# [bundle]
# identifier = "baxterjo_webapp"
# icon = ["./public/img/favicon.png"]

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true
index_on_404 = true

# Which files or dirs will be monitored
watch_path = ["src", "public", "public/css"]

# Include style or script assets
[web.resource]

# CSS style file
style = ["tailwind.css"]

# Javascript code file
script = [
    # "lib/jquery/jquery.min.js",
    # "lib/bootstrap/js/bootstrap.min.js",
    # "js/main.js",
]

[web.resource.dev]

# Same as [web.resource], but for development servers

# CSS style file
style = []

# JavaScript files
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
