[application]

# App name
name = "baxterjo_webapp"

# The Dioxus platform to default to
default_platform = "web"

# `build` & `serve` output path
out_dir = "docs"

# The static resource path
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Jordan Baxter"


[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true
index_on_404 = true

# Which files or dirs will be monitored
watch_path = ["src", "public", "public/css", "site_content"]

# Include style or script assets
[web.resource]

# CSS style file
style = [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css",
    "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css",
    "https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700",
    "/css/style.css",
]

# Javascript code file
script = [
    "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js",
]

[web.resource.dev]

# Same as [web.resource], but for development servers

# CSS style file
style = []

# JavaScript files
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
