title = "Open Source Contributions"
thumbnail = "/img/software_projects/open_source/open_source.png"
description = "This is a bucket for small open source contributions."
date_added = 2023-12-07
priority_level = 0
