title = "Pong's Revenge"
thumbnail = "/assets/img/software_projects/pongs_revenge/pongsrevenge_resize.gif"
description = "This pong recreation was built using openFrameworks in C++"
date_added = 2018-01-02
priority_level = 0
