title = "Antenna Simulator"
thumbnail = "/img/software_projects/ant_sim/antennasimulator.gif"
description = "An antenna simulation application written in python that uses the tkinter toolkit to render a GUI."
date_added = 2020-03-02
priority_level = 0
